// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Sistema_Ventas.Data;

#nullable disable

namespace Proyecto_Sistema_Ventas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Administrador", b =>
                {
                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nivel_Acceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_Usuario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Categoria", b =>
                {
                    b.Property<int>("id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_Categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Cliente", b =>
                {
                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_Usuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Comentario", b =>
                {
                    b.Property<int>("id_Comentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("id_Comentario");

                    b.HasIndex("id_Usuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Detalle_Pedido", b =>
                {
                    b.Property<int>("id_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("id_Producto")
                        .HasColumnType("int");

                    b.HasKey("id_Detalle");

                    b.HasIndex("id_Pedido");

                    b.HasIndex("id_Producto");

                    b.ToTable("Detalle_Pedidos");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Factura", b =>
                {
                    b.Property<int>("id_Factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha_Emision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Numero_Factura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_Pedido")
                        .HasColumnType("int");

                    b.HasKey("id_Factura");

                    b.HasIndex("id_Pedido")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Pedido", b =>
                {
                    b.Property<int>("id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion_Entrega")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Fecha_Entrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nota_Personalizacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Entrega")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("id_Pedido");

                    b.HasIndex("id_Usuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Producto", b =>
                {
                    b.Property<int>("id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Personalizable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("id_Categoria")
                        .HasColumnType("int");

                    b.HasKey("id_Producto");

                    b.HasIndex("id_Categoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Usuario", b =>
                {
                    b.Property<int>("id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Administrador", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Usuario", "Usuario")
                        .WithOne("Administrador")
                        .HasForeignKey("Proyecto_Sistema_Ventas.Models.Administrador", "id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Cliente", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Proyecto_Sistema_Ventas.Models.Cliente", "id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Comentario", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Cliente", "Cliente")
                        .WithMany("Comentarios")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Detalle_Pedido", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Sistema_Ventas.Models.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Factura", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Pedido", "Pedido")
                        .WithOne("Factura")
                        .HasForeignKey("Proyecto_Sistema_Ventas.Models.Factura", "id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Pedido", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Producto", b =>
                {
                    b.HasOne("Proyecto_Sistema_Ventas.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("id_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Cliente", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Proyecto_Sistema_Ventas.Models.Usuario", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
